### ISSUE TITLE
Windows to Linux path translation issue

### ISSUE THREAD

**Issue by pipe01** [docker/compose-cli#1593]
**Description**

When deploying from a Windows machine to a Linux server, a bind mount with an absolute Linux path gets resolved to a Windows path when doing `docker compose up`, which leads to an error because the file "C:\etc\whatever" doesn't exist on the LInux server.

**Steps to reproduce the issue:**
1. Create a docker-compose.yaml with the following
```
services:
  traefik:
    image: traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
```
2. Run `docker compose up`

**Describe the results you received:**

`Error response from daemon: invalid mount config for type "bind": invalid mount path: 'I:/var/run/docker.sock' mount path must be absolute`

**Describe the results you expected:**

The file at `/var/run/docker.sock` to be mounted on the container.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Cloud integration: 1.0.12
 Version:           20.10.5
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:14:53 2021
 OS/Arch:           windows/amd64
 Context:           ganymede
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.15
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       99e3ed8
  Built:            Sat Jan 30 03:18:13 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.9
  GitCommit:        ea765aba0d05254012b0b9e595e995c09186427f
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
**Output of `docker info`:**

```
Client:
 Context:    ganymede
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.6.0)

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 7
 Server Version: 19.03.15
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ea765aba0d05254012b0b9e595e995c09186427f
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.14.138-rancher
 Operating System: RancherOS v1.5.8
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 988.3MiB
 Name: lw-ganymede
 ID: BQ6S:773R:WP3B:TOIW:KYD6:FFSS:CIAM:IHRH:LBTT:N5VQ:3WAB:FAT3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by ndeloof** [comment]
Already fixed in 1.0.13 by https://github.com/docker/compose-cli/pull/1497

**Comment by Jitsusama** [comment]
@ndeloof; I have the latest version of Docker Desktop installed and I'm still seeing this issue, though instead of an error, I am just having the bind get incorrectly setup:

```yaml
services:
  ingress:
    image: traefik:v2.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

That results in this bind mount:

```
PS C:\project> (docker inspect project_ingress_1 | ConvertFrom-Json).HostConfig.Mounts

Type Source                 Target
---- ------                 ------
bind C:\var\run\docker.sock /var/run/docker.sock
```

Any idea what might be going on, or is the fixed release not GA yet? I'm running Docker Desktop version 3.3.3.

**Comment by Jitsusama** [comment]
In case anyone else runs into this, a quick fix for me was adding another \ to the front like so:

```yaml
services:
  ingress:
    image: traefik:v2.4
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
```

That seems to work well for me.
